name: Build and Test with CSV Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11 (Eclipse Adoptium)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adoptium'  # Use 'adoptium' instead of 'adoptopenjdk'

    - name: Build and Test
      run: |
        mvn clean install
        mvn test > result.log

    - name: Convert results to CSV
      run: |
        echo "Test Name,Result" > test_results.csv
        grep -E "Test passed|Test failed" result.log | sed 's/.*\(Test .*\): \(.*\)/\1,\2/' >> test_results.csv

    - name: Upload test results CSV
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.csv
